name: Deploy Portfolio to GitHub Pages

on:
  push:
    branches:
      - main # Change cette branche si nécessaire (ex: "dev")

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout du code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Installe Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "npm"

      # 3. Installer les dépendances
      - name: Install dependencies
        run: npm install

      # 4. Build le projet
      - name: Build project
        run: npm run build

      # 5. Déployer sur GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
